export enum StatusRequestEnum {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  INTERVIEW = "INTERVIEW",
  EVALUATED = "EVALUATED",
  REJECTED = "REJECTED",
  HIRED = "HIRED",
  CANCELLED = "CANCELLED",
}