export enum TrainingLevelEnum {
  BACHELORS = "BACHELOR’S DEGREE",
  POSTGRADUATE = "POSTGRADUATE",
  MASTERS = "MASTER’S DEGREE",
  DOCTORATE = "DOCTORATE",
  TECHNICAL = "TECHNICAL",
  MANAGEMENT = "MANAGEMENT",
}